/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Task Hive API
 * Task Hive API description
 * OpenAPI spec version: 1.0
 */

export interface CreateProjectDto {
  name: string;
  description: string;
  companyOwnerId: string;
}
