/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Task Hive API
 * Task Hive API description
 * OpenAPI spec version: 1.0
 */

export interface CreateUserDto {
  name: string;
  email: string;
  password: string;
  confirmPassword: string;
  avatar: string;
}
