/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Task Hive API
 * Task Hive API description
 * OpenAPI spec version: 1.0
 */

export interface CreateToDoDto {
  id: string;
  title: string;
  description: string;
  isRecurring: boolean;
  recurringTimes: number;
  recurringDeadline: string;
  recurringType: string;
}
