/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Task Hive API
 * Task Hive API description
 * OpenAPI spec version: 1.0
 */

export const UpdateProjectDtoValue = { [key: string]: unknown } as const;
export type UpdateProjectDto = typeof UpdateProjectDtoValue;
