/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Task Hive API
 * API do Task Hive - projetos, tarefas, tarefas avulsas e empresas.

**Autenticação:** esta spec usa HTTP Bearer (JWT). Se o cliente for um BFF com sessão em cookie, o proxy deve enviar `Authorization: Bearer <token>` ao upstream (ou o backend passar a aceitar cookie) — documente o fluxo no deploy.
 * OpenAPI spec version: 1.0
 */

/**
 * Novo status: TODO, DONE, CANCELLED, PAUSED, CREATED
 */
export type ChangeTaskStatusDtoStatus =
  (typeof ChangeTaskStatusDtoStatus)[keyof typeof ChangeTaskStatusDtoStatus];

export const ChangeTaskStatusDtoStatus = {
  TODO: "TODO",
  DONE: "DONE",
  CANCELLED: "CANCELLED",
  PAUSED: "PAUSED",
  CREATED: "CREATED",
} as const;
