/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Task Hive API
 * API do Task Hive - projetos, tarefas, tarefas avulsas e empresas.

**Autenticação:** esta spec usa HTTP Bearer (JWT). Se o cliente for um BFF com sessão em cookie, o proxy deve enviar `Authorization: Bearer <token>` ao upstream (ou o backend passar a aceitar cookie) — documente o fluxo no deploy.
 * OpenAPI spec version: 1.0
 */

export interface CreateUserDto {
  /**
   * Nome do usuário
   * @maxLength 255
   */
  name?: string;
  /**
   * Email único do usuário
   * @maxLength 255
   */
  email: string;
  /**
   * Senha (mín. 8 caracteres, 1 maiúscula, 1 minúscula, 1 número, 1 símbolo)
   * @minLength 8
   * @maxLength 255
   */
  password: string;
  /** Confirmação da senha (deve ser igual a password) */
  confirmPassword: string;
  /** URL ou identificador do avatar */
  avatar?: string;
}
