/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Task Hive API
 * Especificação de placeholder. Substitua pelo JSON OpenAPI exportado do Swagger do backend (ex.: /v3/api-docs).
 * OpenAPI spec version: 1.0.0
 */

export * from "./healthCheck200";
