/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Task Hive API
 * API do Task Hive - projetos, tarefas, tarefas avulsas e empresas.

**Autenticação:** esta spec usa HTTP Bearer (JWT). Se o cliente for um BFF com sessão em cookie, o proxy deve enviar `Authorization: Bearer <token>` ao upstream (ou o backend passar a aceitar cookie) — documente o fluxo no deploy.
 * OpenAPI spec version: 1.0
 */
import type { ProjectStageSummaryOpenApiDto } from "./projectStageSummaryOpenApiDto";
import type { UserIdRefOpenApiDto } from "./userIdRefOpenApiDto";

export interface TaskOpenApiDto {
  id: string;
  name: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  finishDate?: string | null;
  stage?: ProjectStageSummaryOpenApiDto;
  user?: UserIdRefOpenApiDto;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  deletedAt?: string | null;
}
