/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Task Hive API
 * API do Task Hive - projetos, tarefas, tarefas avulsas e empresas.

**Autenticação:** esta spec usa HTTP Bearer (JWT). Se o cliente for um BFF com sessão em cookie, o proxy deve enviar `Authorization: Bearer <token>` ao upstream (ou o backend passar a aceitar cookie) — documente o fluxo no deploy.
 * OpenAPI spec version: 1.0
 */

export interface UpdateProjectStageDto {
  /**
   * Nome da coluna (stage)
   * @maxLength 255
   */
  name?: string;
  /** ID do projeto (bigint) ao qual a coluna pertence */
  projectId?: string;
  /**
   * Ordem de exibição (número >= 0)
   * @minimum 0
   */
  order?: number;
  /** ID da coluna seguinte (bigint), para encadear colunas */
  nextStageId?: string;
  /** ID da coluna anterior (bigint), para encadear colunas */
  prevStageId?: string;
}
