/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Task Hive API
 * API do Task Hive - projetos, tarefas, tarefas avulsas e empresas.

**Autenticação:** esta spec usa HTTP Bearer (JWT). Se o cliente for um BFF com sessão em cookie, o proxy deve enviar `Authorization: Bearer <token>` ao upstream (ou o backend passar a aceitar cookie) — documente o fluxo no deploy.
 * OpenAPI spec version: 1.0
 */
import type { UpdateToDoDtoRecurringType } from "./updateToDoDtoRecurringType";

export interface UpdateToDoDto {
  /**
   * Título da tarefa avulsa
   * @minLength 3
   * @maxLength 255
   */
  title?: string;
  /**
   * Descrição da tarefa
   * @minLength 3
   * @maxLength 5000
   */
  description?: string;
  /** Se true, tarefa é recorrente (type RECURRING); senão PUNCTUAL */
  isRecurring?: boolean;
  /** Número de ocorrências da recorrente (opcional) */
  recurringTimes?: number;
  /** Data limite da recorrência (ISO 8601) */
  recurringDeadline?: string;
  /** Tipo de recorrência: DAILY, WEEKLY, MONTHLY */
  recurringType?: UpdateToDoDtoRecurringType;
}
