/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Task Hive API
 * API do Task Hive - projetos, tarefas, tarefas avulsas e empresas.

**Autenticação:** esta spec usa HTTP Bearer (JWT). Se o cliente for um BFF com sessão em cookie, o proxy deve enviar `Authorization: Bearer <token>` ao upstream (ou o backend passar a aceitar cookie) — documente o fluxo no deploy.
 * OpenAPI spec version: 1.0
 */

export interface UpdateSubtaskDto {
  /**
   * Nome da subtarefa
   * @maxLength 255
   */
  name?: string;
  /** ID da tarefa (bigint) à qual a subtarefa pertence */
  taskId?: string;
  /** Descrição da subtarefa */
  description?: string;
}
